### ISSUE TITLE
[Frontend] [Component] ServiceCard.jsx and ServiceCard.css files

### ISSUE THREAD

**Issue by egodschalk** [arturoa925/knowitforward-frontend#14]
## USER STORY

AS A professional service provider,
I WANT a platform to offer my services  with the proceeds going directly to a charitable cause,
SO THAT I can contribute to the community while sharing my expertise and supporting a cause I care about.

## ACCEPTANCE CRITERIA

- [ ] call to get service data
   - should only render cards that are active and the time left 
- [ ] Title
- [ ] Profile picture
- [ ] status
- [ ] price
- [ ] scheduled date
- [ ] time left: calculated from offer end date - now
- [ ] Charity
- [ ] conditional rendering of button
    - book/done/cancel/pay
    - book/done/cancel will make a put call to api/services/:id with the body as {action: book/done/cancel}
    - the pay button will be rendered with the stripe payment link in the <Link to="servicedata.paymenturl">
- [ ] Description
- [ ] styling

**Comment by amritank** [comment]
The buttons should have the following data properties so that these can be passed to the backend
- Book button 
-       data-current-status=active data-tostatus=booked
-
